sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo-source # get the source code 
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  target-branch: master # put the page to where it should be
  keep-history: true
  on:
    branch: hexo-source 
  local-dir: public